### ISSUE TITLE
ВШЭП и SmartBridge

### ISSUE THREAD

**Issue by klezyk** [JohnHenrySpike/kalkan-crypt#5]
Добрый день, спасибо за отличную работу.

Подскажите, решали ли проблему The security token could not be authenticated or authorized в ответ от тестового сервера SmartBridge https://195.12.113.7/bip-sync-wss-gost? Подпись полностью идентичная в SOAP и заявке на портале SmartBridge. До тех поддержки не достучаться...

**Comment by JohnHenrySpike** [comment]
Добрый день. 
Благодарю за отзыв )
К сожалению нет - такой ошибки не возникало.
`The security token could not be authenticated or authorized` - такое сообщение в виде `SoapFault` возвращается?

**Comment by klezyk** [comment]
`<soap:Envelope
	xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
	<soap:Body>
		<soap:Fault>
			<faultcode
				xmlns:ns1="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">ns1:FailedAuthentication
			</faultcode>
			<faultstring>The security token could not be authenticated or authorized</faultstring>
		</soap:Fault>
	</soap:Body>
</soap:Envelope>`

**Comment by JohnHenrySpike** [comment]
Да точно - такого небыло.
Могу только предложить попробовать обратится к владельцу сервиса, возможно их админы смогут помочь быстрее поддержки.
